version: "3.8"
services:

  dbpostgresql:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d